branch-defaults:
  default:
    environment: eb-django-app-dev
global:
  application_name: eb_django_app
  default_ec2_keyname: aws-eb
  default_platform: Python 2.7
  default_region: ap-southeast-1
  profile: eb-cli
  sc: null
